routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware'=> ['web' => 'auth']],function (){


	Route::resource('product','product');
Route::resource('category','cate');
	Route::get('home',function(){
if(Auth::user()->admin == 0){
	return view('home');
}else{
	$user=\App\User::all();
return 	 view('admin.index', compact('user'));

}
	});
		});

Route::get('order/{or}', 'HomeController@ordera');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','admin',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class category extends Model
{
    //
}

app/pro.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class pro extends Model
{
    //
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\pro;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
    
    public function ordera($id){

$a=pro::orderBy('id',$id)->get();
       return response::json($a);
}
}

app/Http/Controllers/aj.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class aj extends Controller
{
    //
}

app/Http/Controllers/cate.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\category;
use Illuminate\Support\Facades\Auth;

class cate extends Controller
{
     /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
     public function index()
    {
    	        if(Auth::user()->admin == 1){

        $categorys=category::all();
        return view('admin.category.index',compact('categorys'));
     }
      else 
        {
            return view('error404');

                }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
    	    	        if(Auth::user()->admin == 1){

        return view('admin.category.creat');
          }
      else 
        {
            return view('error404');

                }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
"name"=>"required",
  ]);
        $pro=new category();
        $pro->name=$request->input('name');
        $pro->save();
        return redirect('home') ;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
    	    	    	        if(Auth::user()->admin == 1){

          $categories=category::find($id);   

      $categories->delete();
      return back();  
  }
      else 
        {
            return view('error404');

                }
    }
}

app/Http/Controllers/product.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\pro;
use Image;
 use App\category;
use Illuminate\Support\Facades\Auth;

class product extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(Auth::user()->admin == 1){
        $products=pro::paginate(5);
        
        return view('admin.product.index',compact("products"));}

        else 
        {
            return view('error404');

                }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
                if(Auth::user()->admin == 1){

        $cat=category::pluck('name','id');
        return view('admin.product.create',compact('cat'));
        }
        else 
        {
            return view('error404');

        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
'pro_name'=>'required',
'pro_code'=>'required',
'pro_price'=>'required',
'pro_info'=>'required',
'spl_price'=>'required',
'image'=>'required|mimes:jpg,png,jpeg|max:1000',

        ]);
        $pro=new pro();
            $pro->pro_name=$request->input('pro_name');

            $pro->pro_code=$request->input('pro_code');

            $pro->pro_price=$request->input('pro_price');

            $pro->pro_info=$request->input('pro_info');
            $pro->stook=$request->input('stook');

            $pro->categories_id=$request->input('categories_id');
            $pro->spl_price=$request->input('spl_price');
           

        if($request->hasFile('image')){
          $img=$request->image;
    $filename=time() ."_".$img->getClientOriginalName();
    $localtion=public_path('image/'.$filename);
      //$img->move($localtion);
      image::make($img)->resize(1000,1000)->save($localtion);
     
      }

      $pro->image=$filename; 

    $pro->save();
    return redirect('home');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {                if(Auth::user()->admin == 1){

        $products=pro::find($id);
        return view('admin.product.edit',compact('products'));
   }
        else 
        {
            return view('error404');

        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
   if(Auth::user()->admin == 1){
        $productdelete=pro::find($id);   
        unlink('image/'.$productdelete->image);

      $productdelete->delete();
      return back();;   
    } 

        else 
        {
            return view('error404');

        }
}

}

resources/views/admin/category/creat.blade.php
@extends('admin.master')
@section('title','Add categorys')
@section('content')
	<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4 text-center">
        <h1>Add categorys</h1>
<div class="col-md-6">
	<div class="panel-body">
		<form action="{{route('category.store')}}" method="post" role="form"  enctype="multipart/form-data">
			<legend>Add categorys</legend>
			{{csrf_field()}}
			<div class="form-group {{$errors->has('name')?'has-error':''}}">
				<label for="name">product Name</label>
				<input type="text" name="name" id="name"  class="form-control" >
				<span class="text-danger">{{$errors->first('name')}}</span>
			</div>
			
<button type="submit" class="btn btn-info">Add product</button>
		</form>	
	</div>
</div>
        
        </main>
@Endsection

resources/views/admin/category/index.blade.php
@extends('admin.master')
@section('title','List categorys')
@section('content')
	<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
        <h1>List category</h1>
        <a href="{{route('category.create')}}" class="btn btn-info">Add category</a>
<table class="table">
	<tr>
		<thead>
		<td>id</td>
		<td>name</td>
	<td>control</td>
</thead>
<tbody>
	</tr>
@foreach($categorys  as $category)
	<tr>
<td>{{$category->id}}</td>
<td>{{$category->name}}</td>
<td>	
	<form action="{{route('category.destroy',$category->id)}}" method="post">
	{{csrf_field()}}
	{{method_field('DELETE')}}
	<input type="submit" class="btn btn-danger" value="DELETE"> 
    </form>
</td>

	
	</tr>
	@endforeach
</tbody>
</table>

        
        </main>
@Endsection

resources/views/admin/index.blade.php
@extends('admin.master')
@section('title','admin')
@section('content')<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Dashboard</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
              data here
            </div>
          </div>
<div class="container">
</div>

        
        </main>
@Endsection

resources/views/admin/master.blade.php
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>@yield('title','admin')</title>

    <!-- Bootstrap core CSS -->
    <link href="{{asset('dist/css/bootstrap.min.css')}}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{{asset('dist/css/dashboard.css')}}" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
      <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">mo</a>
      <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
      <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
          <a class="nav-link" href="#">Sign out</a>
        </li>
      </ul>
    </nav>

    <div class="container-fluid">
      <div class="row">
       @include('admin.nav') 

        @yield('content')


              </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->


    <script src="{{asset('dist/js/popper.min.js')}}"></script>
    <script src="{{asset('dist/js/bootstrap.min.js')}}"></script>
    <!-- Icons -->
   

    <!-- Graphs -->
   
  </body>
</html>
x

resources/views/admin/nav.blade.php
 <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link active" href="#">
                  <span data-feather="home"></span>
                  Dashboard <span class="sr-only">(current)</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{url('product/create')}}">
                  <span data-feather="file"></span>
                  Add Products
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{url('product')}}">
                  <span data-feather="shopping-cart"></span>
                List Products
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{url('category')}}">
                  <span data-feather="users"></span>
                  Categoiry
                </a>
              </li>
            </ul>
          </div>
        </nav>

resources/views/admin/product/create.blade.php
@extends('admin.master')
@section('title','Add product')
@section('content')
	<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4 text-center">
        <h1>Add product</h1>
<div class="col-md-6">
	<div class="panel-body">
		<form action="{{route('product.store')}}" method="post" role="form"  enctype="multipart/form-data">
			<legend>Add product</legend>
			{{csrf_field()}}
			<div class="form-group {{$errors->has('pro_name')?'has-error':''}}">
				<label for="pro_name">product Name</label>
				<input type="text" name="pro_name" id="pro_name"  class="form-control" >
				<span class="text-danger">{{$errors->first('pro_name')}}</span>
			</div>
				 <div class="form-group {{$errors->has('pro_code')?'has-error':''}}">
				<label for="pro_code">code</label>
				<input type="text" name="pro_code" id="pro_code"  class="form-control" >
				<span class="text-danger">{{$errors->first('pro_code')}}</span>
			     </div>
				   <div class="form-group {{$errors->has('pro_price')?'has-error':''}}">
				<label for="pro_price">price</label>
				<input type="text" name="pro_price" id="pro_price"  class="form-control" >
				<span class="text-danger">{{$errors->first('pro_price')}}</span>
			       </div>

			          <div class="form-group {{$errors->has('stook')?'has-error':''}}">
				<label for="stook">stook</label>
				<input type="text" name="stook" id="stook"  class="form-control" >
				<span class="text-danger">{{$errors->first('stook')}}</span>
			       </div>



				    <div class="form-group {{$errors->has('pro_info')?'has-error':''}}">
				<label for="pro_info">Description</label>
				<textarea  name="pro_info" id="pro_info"  class="form-control"  rows="5"></textarea> 
				<span class="text-danger">{{$errors->first('pro_info')}}</span>
			        </div>


    <div class="form-group {{$errors->has('categories_id')?'has-error':''}}">
				<label for="categories_id">Catgeroy</label>

				<select name="categories_id" id="categories_id">
					@foreach($cat as  $id=>$cats)
					<option value="{{$id}}">{{$cats}}</option>
					@endforeach
				</select>

				<span class="text-danger">{{$errors->first('categories_id')}}</span>
			        </div>
 


			           <div class="form-group {{$errors->has('image')?'has-error':''}}">
				<label for="image">image</label>
				<input type="file" name="image" id="image"  class="form-control" >
				<span class="text-danger">{{$errors->first('image')}}</span>
			           </div> 

                         <div class="form-group {{$errors->has('spl_price')?'has-error':''}}">
				<label for="spl_price">sale price</label>
				<input type="text" name="spl_price" id="spl_price"  class="form-control" >
				<span class="text-danger">{{$errors->first('spl_price')}}</span>
			             </div>
<button type="submiy" class="btn btn-info">Add product</button>
		</form>	
	</div>
</div>
        
        </main>
@Endsection

resources/views/admin/product/index.blade.php
@extends('admin.master')
@section('title','List Product')
@section('content')
	<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
        <h1>List Product</h1>
        <div class="large-3 columns">

        <select name="filter_id" id="filterValue">
              <option value="ASC">ASC</option>
              <option value="DESC">DESC</option>

        </select>


    </div>
<table class="table" id="aa">
	<tr>
		<thead>
		<td>id</td>
	    <td>image</td>
		<td>name</td>
		<td>price</td>
		<td>cager</td>
		<td>contoller</td>
</thead>

	</tr>

	<tbody>
@foreach($products  as $product)
	<tr>
<td>{{$product->id}}</td>
<td><img src="{{url('image',$product->image)}}" width="80" height="80"></td>
<td>{{$product->pro_name}}</td>
<td>{{$product->pro_price}}</td>
<td>cate</td>
<td>
	<form action="{{route('product.destroy',$product->id)}}" method="post">
	{{csrf_field()}}
	{{method_field('DELETE')}}
	<input type="submit" class="btn btn-danger" value="DELETE"> 
    </form>
 <a class="btn btn-success" href="{{route('product.edit',$product->id)}}">Edit</a>
</td>
	</tr>
	@endforeach
</tbody>
</table>

        
        </main>
        <script type="text/javascript" src="{{asset('js/jquery.js')}}"></script>

          <script>
    $(document).ready(function(){

    $('#filterValue').change(function(){
          var teach_id = $('#filterValue option:selected').attr('value');
            
      $.ajax({
    type:'GET',
        url:'{{url("order")}}/'+  teach_id ,
    dataType:'json',

    success:function(data){
    	console.log(data.length);
    	var a='';
    	a+="<thead>";
		a+="<td>id</td>";
	    a+="<td>image</td>";
		a+="<td>name</td>";
		a+="<td>price</td>";
		a+="<td>cager</td>";
		a+="<td>contoller</td>";
		a+="</thead>";

           for(var i=0;i<data.length;i++){
	
a+="<tr>";
a+="<td>";
a+=data[i].id;
a+="</td>";
a+="<td>";
a+="<img src='image/"+data[i].image+"'  width='80' height='80'>";  
a+="</td>";
a+="<td>";
a+=data[i].pro_name;
a+="</td>";
a+="<td>";
a+=data[i].pro_price;
a+="</td>";
a+="<td>";
a+=data[i].id;
a+="</td>";
a+="<td>";
a+="<form action='{{route('product.destroy',"+data[i].id+")}}' method='post'>";
 a+='{{csrf_field()}}';
 a+='{{method_field("DELETE")}}';	
a+="<input type='submit' class='btn btn-danger' value='DELETE'> ";	
a+= "</form>";
a+="<a class='btn btn-success' href='{{route('product.edit',"+data[i].id+")}}'>Edit</a>";
a+="</td>";


a+="</tr>";
                               $("#aa").html(a);
   }
               // $("#aa").html(data);
    },
   });  
alert(teach_id);
            
    });
return false;
     });

    </script>
@Endsection

resources/views/error404.blade.php
	<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

	<title>404 </title>

	<!-- Google font -->
	<link href="https://fonts.googleapis.com/css?family=Montserrat:200,400,700" rel="stylesheet">

	<!-- Custom stlylesheet -->
	<link type="text/css" rel="stylesheet" href="{{asset('css/style.css')}}" />

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->

</head>

<body>

	<div id="notfound">
		<div class="notfound">
			<div class="notfound-404">
				<h1>Oops!</h1>
				<h2>404 - The Page can't be found</h2>
			</div>
			<a href="#">Go TO Homepage</a>
		</div>
	</div>

</body><!-- This templates was made by Colorlib (https://colorlib.com) -->

</html>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @guest
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>